### ISSUE TITLE
a reset button ? 

### ISSUE THREAD

**Issue by fakirsu** [CharlieEtienne/t2s#54]
Hello,

Thanks to the developers for this great tool!! Very convenient for me.

Unless I am mistaken, there is no reset button.
Let me explain: to erase the text and start another one, I have to select and erase, or else use the Delete key.
Maybe a ''reset'' button would be useful.

**Comment by CharlieEtienne** [comment]
Hi @fakirsu,

You're not mistaken. Actually I do Tab or Shift + Tab and then Ctrl + A and Delete

I feel ok this way  in my daily work but sure, it would be even faster if I added a shortcut like Ctrl + Q maybe to erase text + auto focus text area.

Give me a couple of days and I'll release it.

**Comment by CharlieEtienne** [comment]
You can update your project (`git pull`), you'll find a new button in editor with a shortcut (`Ctrl + Q`) 😉

**Comment by fakirsu** [comment]
what a nice button ;-)
Bien joué !
